[package]
name = "example"
version = "0.1.0"
authors = ["WebeWizard <webewizard@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.35.1", features = [] }

webe_web = { path = "../webe_web" }