[package]
name = "example"
version = "0.1.0"
authors = ["WebeWizard <webewizard@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.14.1"

webe_auth = { path = "../webe_auth" }
webe_web = { path = "../webe_web" }