[package]
name = "webe_web"
version = "0.1.0"
authors = ["WebeWizard <webewizard@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-utils = "0.6.6"
limit_read = "0.2.0"
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"