//! Typed error values for WebeID operations.
//!
//! # Examples
//!
//! ```
//! use webe_id::{NodeId, NodeIdError};
//!
//! let error = NodeId::new(999).unwrap_err();
//! match error {
//!     NodeIdError::OutOfRange { value } => assert_eq!(value, 999),
//!     _ => unreachable!("no other NodeIdError variants exist today"),
//! }
//! ```

use std::error::Error;
use std::fmt;

use crate::node::NodeId;

/// Failure returned when a node identifier does not fit the WebeID layout.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum NodeIdError {
    /// The provided node value was outside the supported `0..=255` range.
    OutOfRange {
        /// The rejected node value.
        value: u16,
    },
}

impl fmt::Display for NodeIdError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::OutOfRange { value } => write!(
                formatter,
                "node identifier {value} is outside the supported 0..=255 range"
            ),
        }
    }
}

impl Error for NodeIdError {}

/// Failure returned when decomposed WebeID components cannot be encoded.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum WebeIdComponentsError {
    /// The time component exceeds the 40-bit millisecond field.
    TimeRangeExceeded {
        /// The rejected millisecond component.
        time_millis: u64,
        /// The maximum millisecond component that can be encoded.
        max_millis: u64,
    },
}

impl fmt::Display for WebeIdComponentsError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TimeRangeExceeded {
                time_millis,
                max_millis,
            } => write!(
                formatter,
                "time component {time_millis}ms exceeds the maximum WebeID value of {max_millis}ms"
            ),
        }
    }
}

impl Error for WebeIdComponentsError {}

/// Failure returned while parsing an external WebeID representation.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum ParseWebeIdError {
    /// A byte slice did not contain exactly eight big-endian bytes.
    InvalidByteLength {
        /// The required byte length.
        expected: usize,
        /// The provided byte length.
        actual: usize,
    },
    /// Decimal text was empty, non-numeric, or outside the `u64` range.
    InvalidDecimal {
        /// The rejected input.
        input: String,
    },
    /// Hexadecimal text was empty, non-hexadecimal, or outside the `u64` range.
    InvalidHex {
        /// The rejected input.
        input: String,
    },
}

impl fmt::Display for ParseWebeIdError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidByteLength { expected, actual } => write!(
                formatter,
                "WebeID byte input must contain {expected} bytes, but {actual} were provided"
            ),
            Self::InvalidDecimal { input } => {
                write!(formatter, "WebeID decimal input '{input}' is not valid")
            }
            Self::InvalidHex { input } => {
                write!(formatter, "WebeID hexadecimal input '{input}' is not valid")
            }
        }
    }
}

impl Error for ParseWebeIdError {}

/// Failure returned while constructing a [`crate::Generator`].
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum BuildGeneratorError {
    /// The configured node identifier is outside the supported range.
    InvalidNode(NodeIdError),
    /// The configured epoch is later than the currently observed clock time.
    EpochInFuture,
    /// The currently observed duration since the epoch exceeds the 40-bit field.
    TimeRangeExceeded {
        /// The rejected elapsed millisecond duration.
        elapsed_millis: u128,
        /// The maximum elapsed millisecond duration that can be encoded.
        max_millis: u64,
    },
    /// A restart marker was generated by a different node.
    RestartMarkerNodeMismatch {
        /// The node encoded in the marker.
        marker_node: NodeId,
        /// The node configured for the new generator.
        generator_node: NodeId,
    },
    /// A restart marker is not strictly behind the currently observed duration.
    RestartMarkerNotBehindCurrentTime {
        /// The marker's encoded millisecond duration.
        marker_millis: u64,
        /// The currently observed millisecond duration.
        current_millis: u64,
    },
}

impl From<NodeIdError> for BuildGeneratorError {
    fn from(error: NodeIdError) -> Self {
        Self::InvalidNode(error)
    }
}

impl fmt::Display for BuildGeneratorError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidNode(error) => write!(formatter, "invalid WebeID node: {error}"),
            Self::EpochInFuture => write!(
                formatter,
                "the WebeID epoch is later than the currently observed time"
            ),
            Self::TimeRangeExceeded {
                elapsed_millis,
                max_millis,
            } => write!(
                formatter,
                "elapsed duration {elapsed_millis}ms exceeds the WebeID maximum of {max_millis}ms"
            ),
            Self::RestartMarkerNodeMismatch {
                marker_node,
                generator_node,
            } => write!(
                formatter,
                "restart marker node {marker_node} does not match configured node {generator_node}"
            ),
            Self::RestartMarkerNotBehindCurrentTime {
                marker_millis,
                current_millis,
            } => write!(
                formatter,
                "restart marker time {marker_millis}ms must be strictly behind current time {current_millis}ms"
            ),
        }
    }
}

impl Error for BuildGeneratorError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::InvalidNode(error) => Some(error),
            Self::EpochInFuture
            | Self::TimeRangeExceeded { .. }
            | Self::RestartMarkerNodeMismatch { .. }
            | Self::RestartMarkerNotBehindCurrentTime { .. } => None,
        }
    }
}

/// Failure returned while generating a WebeID.
///
/// # Examples
///
/// ```
/// use webe_id::GenerateError;
///
/// let error = GenerateError::SequenceCapacityExhausted { time_millis: 42 };
/// assert!(error.is_temporarily_recoverable());
/// ```
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum GenerateError {
    /// The observed clock time is earlier than the configured epoch.
    EpochInFuture,
    /// The observed duration since the epoch exceeds the 40-bit field.
    TimeRangeExceeded {
        /// The rejected elapsed millisecond duration.
        elapsed_millis: u128,
        /// The maximum elapsed millisecond duration that can be encoded.
        max_millis: u64,
    },
    /// The observed clock moved behind the last millisecond used for generation.
    ClockRewind {
        /// The currently observed elapsed millisecond duration.
        observed_millis: u64,
        /// The last elapsed millisecond duration used to emit a WebeID.
        last_millis: u64,
    },
    /// All 65,536 sequence values were consumed for the observed millisecond.
    SequenceCapacityExhausted {
        /// The exhausted elapsed millisecond duration.
        time_millis: u64,
    },
}

impl GenerateError {
    /// Returns `true` when retrying after time advances may allow generation to resume.
    pub fn is_temporarily_recoverable(&self) -> bool {
        matches!(
            self,
            Self::ClockRewind { .. } | Self::SequenceCapacityExhausted { .. }
        )
    }
}

impl fmt::Display for GenerateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EpochInFuture => write!(
                formatter,
                "the observed clock time is earlier than the configured WebeID epoch"
            ),
            Self::TimeRangeExceeded {
                elapsed_millis,
                max_millis,
            } => write!(
                formatter,
                "elapsed duration {elapsed_millis}ms exceeds the WebeID maximum of {max_millis}ms"
            ),
            Self::ClockRewind {
                observed_millis,
                last_millis,
            } => write!(
                formatter,
                "observed time {observed_millis}ms is behind the last generated time {last_millis}ms"
            ),
            Self::SequenceCapacityExhausted { time_millis } => write!(
                formatter,
                "all WebeID sequence values are exhausted for {time_millis}ms"
            ),
        }
    }
}

impl Error for GenerateError {}
